[build]
  command = "npm run generate"
  functions = "netlify/functions"
  publish = ".output/public" 
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200