[build]
  command = "npm run generate"
  functions = "netlify/functions"
  publish = ".output/public" 

[[redirects]]
  from = "/favicon.svg"
  to   = "/favicon.svg"
  status = 200
  force  = true

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200