# netlify.toml
[build]
command = "npm run build"
publish = ".output/public"

[functions]
directory = ".netlify/functions"
external_node_modules = ["@nuxt", "@nuxt/kit"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200
