// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/22/2025, 1:04:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/emmta/Local Sites/newportfolio/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/plugins/**/*.{js,ts,mjs}","C:/Users/emmta/Local Sites/newportfolio/src/composables/**/*.{js,ts,mjs}","C:/Users/emmta/Local Sites/newportfolio/src/utils/**/*.{js,ts,mjs}","C:/Users/emmta/Local Sites/newportfolio/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emmta/Local Sites/newportfolio/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;